platform :ios, :deployment_target => "7.0"
pod 'Talool-API', :git => "https://github.com/talool/talool-api-ios.git", :tag => "v1.3.14"
pod 'Braintree', "= 3.1.3"
pod 'Facebook-iOS-SDK', "= 3.23.2"
pod 'FontAwesomeKit', "= 2.1.8"
pod 'GoogleAnalytics-iOS-SDK', "= 3.0.9"
pod 'EAIntroView', "= 2.6.3"
pod 'REMenu', "= 1.10"
pod 'SVProgressHUD', "= 1.0"
pod 'TSMessages', "= 0.9.10"
pod 'SDWebImage', "= 3.7.1"
pod 'UIActivityIndicator-for-SDWebImage', "= 1.2"