/**
 * Autogenerated by Thrift Compiler (0.8.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import <TProtocol.h>
#import <TApplicationException.h>
#import <TProtocolUtil.h>
#import <TProcessor.h>
#import <TObjective-C.h>


@interface Message : NSObject <NSCoding> {
  NSString * __text;
  NSString * __date;

  BOOL __text_isset;
  BOOL __date_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=text, setter=setText:) NSString * text;
@property (nonatomic, retain, getter=date, setter=setDate:) NSString * date;
#endif

- (id) init;
- (id) initWithText: (NSString *) text date: (NSString *) date;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (NSString *) text;
- (void) setText: (NSString *) text;
#endif
- (BOOL) textIsSet;

#if !__has_feature(objc_arc)
- (NSString *) date;
- (void) setDate: (NSString *) date;
#endif
- (BOOL) dateIsSet;

@end

@protocol BulletinBoard <NSObject>
- (void) add: (Message *) msg;  // throws TException
- (NSMutableArray *) get;  // throws TException
@end

@interface BulletinBoardClient : NSObject <BulletinBoard> {
  id <TProtocol> inProtocol;
  id <TProtocol> outProtocol;
}
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface BulletinBoardProcessor : NSObject <TProcessor> {
  id <BulletinBoard> mService;
  NSDictionary * mMethodMap;
}
- (id) initWithBulletinBoard: (id <BulletinBoard>) service;
- (id<BulletinBoard>) service;
@end

@interface idlConstants : NSObject {
}
@end
