/**
 * Autogenerated by Thrift Compiler (0.9.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"
#import "TObjective-C.h"


typedef int64_t Timestamp;

@interface ServiceException : NSException <NSCoding> {
  int32_t __errorCode;
  NSString * __errorDesc;

  BOOL __errorCode_isset;
  BOOL __errorDesc_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=errorCode, setter=setErrorCode:) int32_t errorCode;
@property (nonatomic, retain, getter=errorDesc, setter=setErrorDesc:) NSString * errorDesc;
#endif

- (id) init;
- (id) initWithErrorCode: (int32_t) errorCode errorDesc: (NSString *) errorDesc;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (int32_t) errorCode;
- (void) setErrorCode: (int32_t) errorCode;
#endif
- (BOOL) errorCodeIsSet;

#if !__has_feature(objc_arc)
- (NSString *) errorDesc;
- (void) setErrorDesc: (NSString *) errorDesc;
#endif
- (BOOL) errorDescIsSet;

@end

@interface Merchant : NSObject <NSCoding> {
  NSString * __name;
  NSString * __email;

  BOOL __name_isset;
  BOOL __email_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=name, setter=setName:) NSString * name;
@property (nonatomic, retain, getter=email, setter=setEmail:) NSString * email;
#endif

- (id) init;
- (id) initWithName: (NSString *) name email: (NSString *) email;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (NSString *) name;
- (void) setName: (NSString *) name;
#endif
- (BOOL) nameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) email;
- (void) setEmail: (NSString *) email;
#endif
- (BOOL) emailIsSet;

@end

@interface Address : NSObject <NSCoding> {
  int64_t __addressId;
  NSString * __address1;
  NSString * __address2;
  NSString * __city;
  NSString * __stateProvinceCounty;
  NSString * __zip;
  NSString * __country;
  Timestamp __created;
  Timestamp __updated;

  BOOL __addressId_isset;
  BOOL __address1_isset;
  BOOL __address2_isset;
  BOOL __city_isset;
  BOOL __stateProvinceCounty_isset;
  BOOL __zip_isset;
  BOOL __country_isset;
  BOOL __created_isset;
  BOOL __updated_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=addressId, setter=setAddressId:) int64_t addressId;
@property (nonatomic, retain, getter=address1, setter=setAddress1:) NSString * address1;
@property (nonatomic, retain, getter=address2, setter=setAddress2:) NSString * address2;
@property (nonatomic, retain, getter=city, setter=setCity:) NSString * city;
@property (nonatomic, retain, getter=stateProvinceCounty, setter=setStateProvinceCounty:) NSString * stateProvinceCounty;
@property (nonatomic, retain, getter=zip, setter=setZip:) NSString * zip;
@property (nonatomic, retain, getter=country, setter=setCountry:) NSString * country;
@property (nonatomic, getter=created, setter=setCreated:) Timestamp created;
@property (nonatomic, getter=updated, setter=setUpdated:) Timestamp updated;
#endif

- (id) init;
- (id) initWithAddressId: (int64_t) addressId address1: (NSString *) address1 address2: (NSString *) address2 city: (NSString *) city stateProvinceCounty: (NSString *) stateProvinceCounty zip: (NSString *) zip country: (NSString *) country created: (Timestamp) created updated: (Timestamp) updated;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (int64_t) addressId;
- (void) setAddressId: (int64_t) addressId;
#endif
- (BOOL) addressIdIsSet;

#if !__has_feature(objc_arc)
- (NSString *) address1;
- (void) setAddress1: (NSString *) address1;
#endif
- (BOOL) address1IsSet;

#if !__has_feature(objc_arc)
- (NSString *) address2;
- (void) setAddress2: (NSString *) address2;
#endif
- (BOOL) address2IsSet;

#if !__has_feature(objc_arc)
- (NSString *) city;
- (void) setCity: (NSString *) city;
#endif
- (BOOL) cityIsSet;

#if !__has_feature(objc_arc)
- (NSString *) stateProvinceCounty;
- (void) setStateProvinceCounty: (NSString *) stateProvinceCounty;
#endif
- (BOOL) stateProvinceCountyIsSet;

#if !__has_feature(objc_arc)
- (NSString *) zip;
- (void) setZip: (NSString *) zip;
#endif
- (BOOL) zipIsSet;

#if !__has_feature(objc_arc)
- (NSString *) country;
- (void) setCountry: (NSString *) country;
#endif
- (BOOL) countryIsSet;

#if !__has_feature(objc_arc)
- (Timestamp) created;
- (void) setCreated: (Timestamp) created;
#endif
- (BOOL) createdIsSet;

#if !__has_feature(objc_arc)
- (Timestamp) updated;
- (void) setUpdated: (Timestamp) updated;
#endif
- (BOOL) updatedIsSet;

@end

@interface Customer : NSObject <NSCoding> {
  int64_t __customerId;
  NSString * __firstName;
  NSString * __lastName;
  NSString * __email;
  NSString * __password;
  Address * __address;
  Timestamp __created;
  Timestamp __updated;

  BOOL __customerId_isset;
  BOOL __firstName_isset;
  BOOL __lastName_isset;
  BOOL __email_isset;
  BOOL __password_isset;
  BOOL __address_isset;
  BOOL __created_isset;
  BOOL __updated_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, getter=customerId, setter=setCustomerId:) int64_t customerId;
@property (nonatomic, retain, getter=firstName, setter=setFirstName:) NSString * firstName;
@property (nonatomic, retain, getter=lastName, setter=setLastName:) NSString * lastName;
@property (nonatomic, retain, getter=email, setter=setEmail:) NSString * email;
@property (nonatomic, retain, getter=password, setter=setPassword:) NSString * password;
@property (nonatomic, retain, getter=address, setter=setAddress:) Address * address;
@property (nonatomic, getter=created, setter=setCreated:) Timestamp created;
@property (nonatomic, getter=updated, setter=setUpdated:) Timestamp updated;
#endif

- (id) init;
- (id) initWithCustomerId: (int64_t) customerId firstName: (NSString *) firstName lastName: (NSString *) lastName email: (NSString *) email password: (NSString *) password address: (Address *) address created: (Timestamp) created updated: (Timestamp) updated;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

#if !__has_feature(objc_arc)
- (int64_t) customerId;
- (void) setCustomerId: (int64_t) customerId;
#endif
- (BOOL) customerIdIsSet;

#if !__has_feature(objc_arc)
- (NSString *) firstName;
- (void) setFirstName: (NSString *) firstName;
#endif
- (BOOL) firstNameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) lastName;
- (void) setLastName: (NSString *) lastName;
#endif
- (BOOL) lastNameIsSet;

#if !__has_feature(objc_arc)
- (NSString *) email;
- (void) setEmail: (NSString *) email;
#endif
- (BOOL) emailIsSet;

#if !__has_feature(objc_arc)
- (NSString *) password;
- (void) setPassword: (NSString *) password;
#endif
- (BOOL) passwordIsSet;

#if !__has_feature(objc_arc)
- (Address *) address;
- (void) setAddress: (Address *) address;
#endif
- (BOOL) addressIsSet;

#if !__has_feature(objc_arc)
- (Timestamp) created;
- (void) setCreated: (Timestamp) created;
#endif
- (BOOL) createdIsSet;

#if !__has_feature(objc_arc)
- (Timestamp) updated;
- (void) setUpdated: (Timestamp) updated;
#endif
- (BOOL) updatedIsSet;

@end

@protocol TaloolService <NSObject>
- (void) registerCustomer: (Customer *) customer password: (NSString *) password;  // throws ServiceException *, TException
@end

@interface TaloolServiceClient : NSObject <TaloolService> {
  id <TProtocol> inProtocol;
  id <TProtocol> outProtocol;
}
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface TaloolServiceProcessor : NSObject <TProcessor> {
  id <TaloolService> mService;
  NSDictionary * mMethodMap;
}
- (id) initWithTaloolService: (id <TaloolService>) service;
- (id<TaloolService>) service;
@end


